# Generated by Django 5.2.10 on 2026-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_order_feedback_payment_vendor_order_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_images/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
